disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Deenz' Dev Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "whale_2.png"
description = "A blog about programming, my personal woes, and whatever else is on my mind.."

[[params.author.links]]
github = "https://github.com/deenzdev/"

[[params.author.links]]
steam = "https://steamcommunity.com/id/ashofcrow/"

[[params.author.links]]
x-twitter = "https://x.com/whacknautiloid"

[[params.author.links]]
spotify = "https://open.spotify.com/user/off-artorias"

["params.author"]
name = "Deenz"
image = "logo.png"
headline = "How the fuck did you get here???"
email = "admin@deenzcan.com"
imageQuality = "96"
bio = "Just some 28 year old doomer writing about random crud."
