[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "QQmrxzplZ4"
weight = 9_999

[[main]]
name = "About"
pageRef = "about"
identifier = "9bYyV4bgci"
weight = 10_999

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "T0FIK59NiF"
weight = 9_999

[[main]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
none = "none"
