[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "QQmrxzplZ4"
weight = 9_999

[[main]]
name = "About"
pageRef = "about"
identifier = "9bYyV4bgci"
weight = 9_999

[[footer]]
none = "none"
