backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: dekaratas/deenz-blog
media_folder: static/img
public_folder: /img
collections:
  - name: "article"
    label: "Articles"
    folder: "content/posts"
    create: true
    path: '{{slug}}/index'
    slug: "{{timestamp}}-{{slug}}"
    sortable_fields: ['date', 'title']
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "showHero", name: "showHero",
         widget: "boolean",
         default: true}
      - {label: "Summary", name: "summary", widget: "text", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Categories", name: "categories", widget: "list", default: ["dev"]}
      - {label: "Featured Image", name: "featured", widget: "image", required: false, path: '{{slug}}/featured'}
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Body"
            name: "body"
            widget: "markdown"
